version: '3.8'
services:
  app:
    image: 'hcmut_spss:0.0.1'
    build:
      context: ./backend-springboot
      dockerfile: Dockerfile
    container_name: hcmut_spss-app
    restart: always
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hcmut-spss.postgres.database.azure.com:5432/postgres?user=lemonHV&password=mtv123@@&sslmode=require
      - SPRING_DATASOURCE_USERNAME=lemonHV
      - SPRING_DATASOURCE_PASSWORD=mtv123@@
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_PORT=8090
      - APP_URL=http://localhost:8090
    volumes:
      - ./src/main/resources/static:/app/static
          
  frontend:
    image: 'hcmut_spss-frontend:0.0.1' 
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
    environment:
      - CHOKIDAR_USERPOLLING=true
      - VITE_API_URL=http://localhost:8090
    volumes:
      - ./frontend-react:/app
      - /app/node_modules

networks:
  default:
    driver: bridge